heat_template_version: 2016-10-14

description: Template create cpanel bundle.

#####################################
# PARAMETERS
#####################################
parameters:
  image:
    type: string
    label: Image name or ID
    description: Image to be used for server. Please use an Centos based image.
  flavor:
    type: string
    label: Flavor
    description: Type of instance (flavor) to be used on the compute instance.
  private_network:
    type: string
    label: Private Network
    description: Setup Private network
  public_network:
    type: string
    label: Public network name or ID
    description: Public network to attach server to.
    default: Public_Network
  username:
    type: string
    label: Set Username
    description: Set username to virtual machine and cpanel bundle.
  password:
    type: string
    label: Set password cpanel
    description: Set password to cpanel bundle.
  neo_type:
    type: json
    label: neo type metadata
    description: Set neo type metadata
    default: {"metadata": {"neo_type": "PLSK"}}
  floating_desc:
    type: string
    label: neo description for floating ip
    description: neo description for floating ip
    default: PLSK

resources:
  secgroup:
    type: OS::Neutron::SecurityGroup
    properties:
      name:
        list_join: [-, [{ get_param: 'OS::stack_name' },neo,secgroup]]
      rules:
        - protocol: icmp
        - protocol: udp
        - protocol: tcp
          port_range_min: 1
          port_range_max: 1
        - protocol: tcp
          port_range_min: 7
          port_range_max: 7
        - protocol: tcp
          port_range_min: 22
          port_range_max: 22
        - protocol: tcp
          port_range_min: 25
          port_range_max: 25
        - protocol: tcp
          port_range_min: 26
          port_range_max: 26
        - protocol: tcp
          port_range_min: 37
          port_range_max: 37
        - protocol: tcp
          port_range_min: 43
          port_range_max: 43
        - protocol: tcp
          port_range_min: 53
          port_range_max: 53
        - protocol: tcp
          port_range_min: 110
          port_range_max: 110
        - protocol: tcp
          port_range_min: 113
          port_range_max: 113
        - protocol: tcp
          port_range_min: 143
          port_range_max: 143
        - protocol: tcp
          port_range_min: 443
          port_range_max: 443
        - protocol: tcp
          port_range_min: 465
          port_range_max: 465
        - protocol: tcp
          port_range_min: 579
          port_range_max: 579
        - protocol: tcp
          port_range_min: 587
          port_range_max: 587
        - protocol: tcp
          port_range_min: 783
          port_range_max: 783
        - protocol: tcp
          port_range_min: 873
          port_range_max: 873
        - protocol: tcp
          port_range_min: 953
          port_range_max: 953
        - protocol: tcp
          port_range_min: 995
          port_range_max: 995
        - protocol: tcp
          port_range_min: 2077
          port_range_max: 2077
        - protocol: tcp
          port_range_min: 2078
          port_range_max: 2078
        - protocol: tcp
          port_range_min: 2079
          port_range_max: 2079
        - protocol: tcp
          port_range_min: 2080
          port_range_max: 2080
        - protocol: tcp
          port_range_min: 2082
          port_range_max: 2082
        - protocol: tcp
          port_range_min: 2083
          port_range_max: 2083
        - protocol: tcp
          port_range_min: 2086
          port_range_max: 2086
        - protocol: tcp
          port_range_min: 2087
          port_range_max: 2087
        - protocol: tcp
          port_range_min: 2089
          port_range_max: 2089
        - protocol: tcp
          port_range_min: 2091
          port_range_max: 2091
        - protocol: tcp
          port_range_min: 2095
          port_range_max: 2095
        - protocol: tcp
          port_range_min: 2096
          port_range_max: 2096
        - protocol: tcp
          port_range_min: 80
          port_range_max: 80
        - remote_mode: remote_group_id

  define_port:
    type: OS::Neutron::Port
    properties:
      admin_state_up: true
      network_id: { get_param: private_network }
      security_groups:
        - {get_resource: secgroup}

  floating:
      type: OS::Neutron::FloatingIP
      properties:
        value_specs: {"description":{get_param: floating_desc}}
        floating_network: {get_param: public_network}
        port_id: {get_resource: define_port}

  cloud_config:
    type: OS::Heat::MultipartMime
    properties:
      parts:
        - config:
            str_replace:
              params:
                $USERNAME : { get_param: username }
                $PASSWORD : { get_param: password }
              template: |
                #cloud-config
                system_info:
                  default_user:
                    name: $USERNAME
                    lock_passwd: true
                    gecos: Instances Interactive User
                    groups: [wheel, adm, systemd-journal]
                    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
                    shell: /bin/bash
                chpasswd:
                  list: |
                    $USERNAME:$PASSWORD,
                    root:$PASSWORD
                  expire: False
                ssh_pwauth: True

  create_vm:
    type: OS::Nova::Server
    properties:
      name: { get_param: 'OS::stack_name' }
      image: {get_param: image}
      metadata: { get_param: [ neo_type, metadata ] }
      flavor: {get_param: flavor}
      networks:
        - port: {get_resource: define_port}
      user_data_format: RAW
      user_data: {get_resource: cloud_config}

outputs:
  user:
    description: User Name
    value: {get_param: username}
  controller:
    description: Controller IP
    value: {get_attr: [floating,floating_ip_address]}
  sec_group:
    description: Security Group
    value:
      list_join: [-, [{ get_param: 'OS::stack_name' },neo,secgroup]]
  vm_id:
    description: VM ID
    value: {get_resource: create_vm}
